### PR TITLE
Add in caregivee home page 

### PR DESCRIPTION
**Pull request by cassandrale179**

### CODE REVIEW

**Comment by Sppurswani** [comment]
One thing I noticed from the screen recording is that clicking on a caregiver goes to the profile page which has the option to change password. I think we should get rid of those textfields.

**Comment by Sppurswani** [comment]
Alternatively, we can build it so the list expands to the caregivers email so there wouldn't be the need to navigate elsewhere (and no we wouldn't have to change the profile page lol)

**Comment by Sppurswani** [comment]
Can we remove the button to add a caregiver? I believe right now its a one-way action and a caregivee cannot add a caregiver

**Comment by cassandrale179** [comment]
> Can we remove the button to add a caregiver? I believe right now its a one-way action and a caregivee cannot add a caregiver

Oh oops I forgot that we discuss it to be one-way. I can definitely remove it before I merged in.

**Review by Sppurswani — APPROVED** [review]

**Pull request merged**
