### PR TITLE
Fix Pratik's home screen

### PR DESCRIPTION
**Pull request by cassandrale179**
- View Caregivee Profile 
 

- View Set Task and Progress
 

- Delete Caregivee
 

- Add a new Caregivee

### CODE REVIEW

**Comment by Sppurswani** [comment]
Thank you including these videos! These screens look amazing !!
> * Delete Caregivee
> 
> 

I think there's a brief moment where my name & Annie Edison showing up twice after the deletion loll - did you notice that @cassandrale179 ?

**Comment by cassandrale179** [comment]
@Sppurswani yes that's a glitch that I have no clue how to fix. It deletes on the database properly, but it seems the ExpandableList didn't catch up on it until a bit later so it re-render the list twice with the old list and updated list. But it self-correct a second later if we force-refresh the page (which is my brute-force attempt to solve this problem). I'll file this as a small bug.

**Review by Sppurswani — APPROVED** [review]
Yay looks nice and organized!

**Comment by Sppurswani** [comment]
> @Sppurswani yes that's a glitch that I have no clue how to fix. It deletes on the database properly, but it seems the ExpandableList didn't catch up on it until a bit later so it re-render the list twice with the old list and updated list. But it self-correct a second later if we force-refresh the page (which is my brute-force attempt to solve this problem). I'll file this as a small bug.

**Comment by Sppurswani** [comment]
> @Sppurswani yes that's a glitch that I have no clue how to fix. It deletes on the database properly, but it seems the ExpandableList didn't catch up on it until a bit later so it re-render the list twice with the old list and updated list. But it self-correct a second later if we force-refresh the page (which is my brute-force attempt to solve this problem). I'll file this as a small bug.

@cassandrale179 I had a similar issue with the Request list earlier, I believe it required you to clear the contents of the list before re-rendering? Not fully sure rn but I can look at it if you file the bug

**Comment by cassandrale179** [comment]
> @cassandrale179 I had a similar issue with the Request list earlier, I believe it required you to clear the contents of the list before re-rendering? Not fully sure rn but I can look at it if you file the bug

Sounds great @Sppurswani . I create a bug here https://github.com/cassandrale179/ci491_project/issues/101 and assigned you. Thanks!

**Pull request merged**
